plugins { id 'com.android.application' }

android {
    namespace 'fr.alexandre.margeplus'
    compileSdk 35
    defaultConfig {
        applicationId 'fr.alexandre.margeplus'
        minSdk 26
        targetSdk 35
        versionCode 20200
        versionName '2.2.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
    lint { abortOnError true; checkReleaseBuilds true }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
